name: "Coverage"

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: "test and comment coverage"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r scripts/requirements-dev.txt
      - name: "Build coverage file"
        run: |
          coverage run -m pytest -m all
          coverage html
          coverage report > pytest-coverage.txt"
      - name: "Upload code coverage report"
        uses: "actions/upload-artifact@v2"
        with:
          name: "code-coverage-report"
          path: "htmlcov/index.html"
      - name: "pytest-coverage-commentator"
        uses: "coroo/pytest-coverage-commentator@v1.0.2"
        with:
          pytest-coverage: "pytest-coverage.txt"
