name: "Coverage"

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: "test and upload coverage"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r scripts/requirements-dev.txt
      - name: "Login to Docker Hub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
      - name: "Start containers"
        run: "docker-compose -f 'docker-compose.yml' up -d --build"
      - name: "Build coverage file"
        run: |
          coverage run -m pytest -m all
          coverage html
          coverage xml
      - name: "Stop containers"
        if: "always()"
        run: "docker-compose -f 'docker-compose.yml' down"
      - name: "Upload code coverage report"
        uses: "actions/upload-artifact@v2"
        with:
          name: "code-coverage-report-html"
          path: "htmlcov/index.html"
      - name: "Upload code coverage report"
        uses: "actions/upload-artifact@v2"
        with:
          name: "code-coverage-report-xml"
          path: "coverage.xml"
  coverage:
    needs: "test"
    name: "download coverage update coverage badge"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v2"
        with:
          name: "code-coverage-report-xml"
      - name: "update badge"
        uses: "coverallsapp/github-action@master"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  tag:
    needs: "coverage"
    runs-on: "ubuntu-latest"
    steps:
      - uses: butlerlogic/action-autotag@1.0.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
