on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Set variables"
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          export CR_PAT=${{ secrets.GITHUB_TOKEN }}
          export DATE_TAG=$(date "+%Y-%m-%dT%H:%M%:%S")
      - name: "Log into GitHub Container Registry"
        uses: "echo $CR_PAT | docker login ghcr.io -u thesammy2010 --password-stdin"
      - name: "build and tag"
        uses: |
          docker build . \
            -t ghcr.io/thesammy2010/gps-tracker:$RELEASE_VERSION \
            -t ghcr.io/thesammy2010/gps-tracker:$DATE_TAG \
            -t ghcr.io/thesammy2010/gps-tracker:latest
      - name: "push"
        uses: |
          docker push ghcr.io/thesammy2010/gps-tracker:$RELEASE_VERSION
          docker push ghcr.io/thesammy2010/gps-tracker:$DATE_TAG
          docker push ghcr.io/thesammy2010/gps-tracker:latest
      - name: "remove images"
        uses: |
          docker rmi ghcr.io/thesammy2010/gps-tracker:$RELEASE_VERSION
          docker rmi ghcr.io/thesammy2010/gps-tracker:$DATE_TAG
          docker rmi ghcr.io/thesammy2010/gps-tracker:latest
      - name: "Setup Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0.2.0"
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          service_account_key: "${{ secrets.GCP_SA_KEY }}"
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy gps-tracker \
            --region europe-west1 \
            --image ghcr.io/thesammy2010/gps-tracker:$RELEASE_VERSION \
            --platform managed \
            --allow-unauthenticated
