name: "Test"

on:
  - "push"

jobs:
  unit:
    name: "test (unit)"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r scripts/requirements-dev.txt
      - name: "test"
        run: "pytest --verbose"
  integration:
    name: "test (integration)"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r scripts/requirements-dev.txt
      - name: "Lint"
        run: "pytest --verbose -m integration"
